### ISSUE TITLE
Inclusão de Tech Recruiters nos projetos da comunidade

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#116]
**Descrição**:
Elaboração de um espaço para inclusão de tech recruiters no servidor SouJunior Lab.

**Motivação**:
Atualmente não temos um espaço dedicado à este profissional em formação, mas caberia na comunidade, pois este pode ajudar no recrutamento dos projetos, realizando entrevistas com os juniores de outras áreas, numa evolução mútua.

**Associações**
Todas as tarefas relacionadas a este épico, estarão com a Label "Inclusão Tech Recruiters", podendo ser utilizado o filtro para fácil navegação entre elas.

**Comment by dansenpir** [comment]
@marimoraes21 e eu conversamos e decidimos o seguinte fluxo:
- 1. O Founder preencherá um formulário com as vagas que precisa preencher;
- 2. A @marimoraes21 atribuirá a tarefa de recrutamento das vagas para um de seus recrutadores mentorados;
- 3. O recrutador (cargo), e somente ele, terá acesso total ao fórum de recrutamento;
- 4. O recrutador cria um post, seguindo o padrão de publicação, no fórum de recrutamento;
- 4. O recrutador realiza entrevistas com os candidatos à(s) vagas(s);
- 5. O recrutador encontra os candidatos que melhor se encaixam a vaga e repassam ao Founder;
- 6. Se o candidato ocupa a vaga, o recrutador tranca/fecha o post no fórum de recrutamento.

@wouerner, precisamos validar contigo se podemos seguir com este fluxo.
Em caso positivo, precisamos entender se o formulário e kanban serão criados por você e repassados para a gente ou se temos liberdade de criar do nosso jeito.

Sendo positivo, os próximos passos são:
- Criar o formulário para preenchimento do Founder;
- Criar kanban para repasse de tarefas aos recrutados pela @marimoraes21;
- Recrutamento de Tech Recruiters para se serem mentorados pela @marimoraes21 e ter essa responsabilidade de recrutamento;
- Documentar o fluxo na Wiki;
- Comunicar os Founder do projeto da mudança.

**Comment by wouerner** [comment]
Aprovado, por favor quebrar em novas issues e linkar aqui.

Ao final da equipe criada preciso me reunir com máximo de pessoa da equipe.

@marimoraes21  fica responsavel por essa parte do projeto acredito eu, com supervisão do @dansenpir .

**Comment by dansenpir** [comment]
Épico finalizado com sucesso!
