### ISSUE TITLE
Descrever os papéis de cada área

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#124]
**Descrição**:
Necessário criar uma página na Wiki descrevendo os papéis de cada uma das áreas presentes durante um projeto de software, levando em consideração os cargos presentes no servidor SouJunior Lab.

**Motivação**:
Atualmente muitos evitam de criar projetos ou até criam, mas não tem muita noção do que cada um é responsável, então essa página visa sanar essa problemática.

**Link da página na Wiki**
https://github.com/SouJunior-Lab/project-list/wiki/%5BDraft%5D-Os-pap%C3%A9is-de-cada-%C3%A1rea-em-um-projeto-de-software

**O que deve ser feito nessa task:**
- [x] Levantamento dos pápeis de cada área nos comentários;
- [x] Validação dos pápeis;
- [x] Em caso de alguma área não coberta, buscar informação externamente;
- [x] Elaboração de uma página na Wiki com o compilado dessas informações;
- [x] Validação da página Wiki.

**Comment by AlynneMartins** [comment]
**UX**

A tarefa do UX Designer, em síntese, é representar o usuário no processo de desenvolvimento de um produto. Trazer a visão dos usuários (ou potenciais usuários) dos softwares.

Sempre com objetivo de trazer simplificação a processos e tarefas para que o software fique cada vez mais próximo ao contexto dos usuários, do negócio e com os melhores caminhos e respostas para que eles tomem as melhores decisões.

Principais responsabilidades de um UX são:

- Pesquisa e entrevista com o usuário
- Benchmarking
- Definição de personas
- Jornada do usuário
- Wireframes (baixa, média e alta fidelidade)
- Protótipos (baixa, média e alta fidelidade)
- Textos para botões e telas
- Testes de usabilidade

**Comment by iltrd** [comment]
Scrum Master: 
É o responsável por garantir que o time Scrum se oriente pelos valores e práticas do Scrum.

Motivação: 
Garantir que a equipe de desenvolvimento siga o processo Scrum e as regras definidas;

Principais Responsabilidades: 

- Remover obstáculos que impeçam a equipe de desenvolvimento de alcançar seus objetivos;
- Orientar a equipe de desenvolvimento na realização de suas tarefas diárias e garantir que a equipe esteja produzindo resultados de alta qualidade;
- Promover a colaboração e o trabalho em equipe entre os membros da equipe;
- Facilitar as cerimônias do Scrum, como a reunião diária de stand-up, revisão do sprint e retrospectiva; 
- Ajudar o Product Owner/Product Manager a gerenciar o backlog do produto e a definir as prioridades do sprint;
- Treinar a equipe de desenvolvimento e o Product Owner/Product Manager nos princípios e práticas ágeis;
- Mediar conflitos e garantir que as diferenças de opinião sejam resolvidas construtivamente;
- Fornecer feedback regular para a equipe de desenvolvimento e o Product Owner/PM;
- Promover a melhoria contínua do processo de desenvolvimento de software.

Temos também os cargos de: 
O **Agile Master** tem o mesmo papel do Scrum Master, mas pode também aplicar práticas além do Scrum como o Método Kanban e Extreme programming (XP), entender de escalabidade SAFE e Nexus (por exemplo) e métricas ágeis.
O **Agile Coach** realiza suporte a outros Scrum Masters/Agile Masters, Product Owners e gestores da organização, apoia os times na execução dos seus papéis, realiza workshops, treina os times, dissemina a agilidade nível organizacional, atua como coach em agilidade, busca alcançar metas, elabora/usa indicadores e métricas ágeis.

**Comment by Rhyan-eduardo** [comment]
Front-end: 
É Responsável por projetar, implementar e manter a interface do usuário de um aplicativo ou site.

As tarefas primárias de um desenvolvedor frontend incluem:

- Projetar e implementar a interface do usuário de um aplicativo ou site.
- Garantir que o design seja atraente, fácil de usar e responsivo em diferentes dispositivos.
- Desenvolver e manter componentes reutilizáveis para facilitar o desenvolvimento e a manutenção do código.
- Trabalhar em colaboração com outros desenvolvedores para garantir a consistência visual e funcional do aplicativo ou site.
- Otimizar a performance da página e garantir que ela seja rápida e eficiente.
- Realizar testes e depurações para garantir a qualidade do código e a funcionalidade do aplicativo ou site.
- Manter-se atualizado com as tecnologias e tendências mais recentes no campo do desenvolvimento frontend.

Suas demandas:

A demanda por profissionais de desenvolvimento frontend tem aumentado significativamente nos últimos anos, devido ao crescente número de empresas que precisam de sites e aplicativos atraentes e interativos para seus negócios. Além disso, com a rápida evolução da tecnologia e das tendências de design, há uma constante necessidade de atualização e inovação na área de frontend, o que cria uma demanda contínua por profissionais altamente qualificados. Como resultado, o mercado de trabalho para desenvolvedores frontend é altamente competitivo e oferece muitas oportunidades de emprego em todo o mundo.

**Comment by dansenpir** [comment]
@AlecLimaDev @BeatrizzRibeiro @marimoraes21 @thainarawulfert 

Teriam algum complemento para contribuir?

**Comment by thainarawulfert** [comment]
Concordo com @AlynneMartins 

Apenas adicionar algumas coisas sobre as ramificações:

**UX Research:**

- Tem como principal função focar nas pesquisas em relação ao produto.

- Utilizam uma variedade de técnicas que podem ser usadas para gerar insights, pode ser feito através de pesquisas qualitativas e quantitativas.

**UX Writing**

- Responsável em falar na mesma língua do seu cliente

- Usam as palavras em seu favor pois é preciso ter muita clareza, ou seja, saber transmitir ao seu usuário quem é sua empresa.

- O mal uso das palavras podem interferir e muito no uso do seu produto com isso a atuação do UX Writing é super importante.

- A estratégia do UX Writing é tornar a navegação simples, amigável e intuitiva.

**UI Design**

- O UI Designer é o responsável por criar e desenvolver estes elementos gráficos, as famosas telas bonitas.

- UI Designer é responsável pela forma como a interface é apresentada.


Espero que agregue em algo, estas de acordo? @AlynneMartins

**Comment by AlecLimaDev** [comment]
**Desenvolvedor Backend**

•	**Desenvolvimento de APIs**: o desenvolvedor backend é responsável por criar e manter as APIs que permitem que o front-end e outros sistemas se comuniquem com o servidor.

•	**Gerenciamento de banco de dados**: o desenvolvedor backend deve entender como trabalhar com bancos de dados e ser capaz de criar e manter esquemas de banco de dados eficientes.

•	**Implementação de segurança**: o desenvolvedor backend deve ser capaz de implementar medidas de segurança para proteger o sistema contra ataques maliciosos.

•	**Otimização de desempenho**: o desenvolvedor backend deve ser capaz de otimizar o desempenho do servidor para garantir que o sistema possa lidar com cargas de trabalho pesadas.

•	**Colaboração com outras equipes**: o desenvolvedor backend deve trabalhar em estreita colaboração com outras equipes, como a equipe de front-end e a equipe de gerenciamento de projeto, para garantir que o sistema funcione de forma fluída.

OBS: Lembrando que isso pode variar de acordo com o tamanho e complexidade do projeto.

**Comment by dansenpir** [comment]
@SouJunior/lab Já tivemos tempo de levantar os papéis de cada área que conhecemos.
Conversei com o @AlecLimaDev e ele acabou abraçando a demanda de criar a página da Wiki.
O que não tiver neste post, mas for um dos cargos do servidor, podemos buscar pela web mesmo.

**Comment by dansenpir** [comment]
@AlecLimaDev precisa de ajuda?

**Comment by AlecLimaDev** [comment]
Por algum motivo quando tento criar na página existente as informações não aparecem. 
Criei uma nova página: https://github.com/SouJunior-Lab/project-list/wiki/Draft.-Pap%C3%A9is-de-cada-%C3%A1rea-em-um-projeto-de-software.

@dansenpir

**Comment by dansenpir** [comment]
@AlecLimaDev, ficou bom, mas faltou cobrir alguns cargos:
- Data Analyst;
- Data Engineer;
- Data Scientist;
- Mobile Developer;
- DevSecOps;
- Infraestructure as Code;
- Site Reliability Engineer;
- Business Analyst.

Dica: use o ChatGPT para aqueles que não tem um bom entendimento.

Você pode separar a página por tópicos, como por exemplo o tópico "Agile" descreveria os cargos "Agile Coach", "Agile Master" e "Scrum Master", assim como o tópico "Product" descreveria os cargos "Businees Analyst", "Product Manager" e "Product Owner", e assim por diante.

**Comment by AlecLimaDev** [comment]
@dansenpir 

Eu gostei da ideia e, como resultado, resolvi testar antes de colocar no rascunho para ver como ia ficar.

Alguns pontos que eu considerei no meu teste:

1. Me imaginei em um momento onde eu só queria as minhas informações para tirar algumas dúvidas rápidas.
2. Estava com pressa.
3. Ctrl+F mais preciso pelo fato das funções estarem separadas e organizadas em fonte maior.

Essa foi alguma das minhas percepções. Caso queiram separar por tópicos, só falar que eu altero. Aguardo resposta.

**Comment by dansenpir** [comment]
@AlecLimaDev, você pode colocar os tópicos como h2 (##) e os títulos das áreas em h3 (###) como já estão.
Acredito que se encaixe no que enxergou, certo?

**Comment by dansenpir** [comment]
@veronicasvalerio, está conseguindo finalizar essa task?
Precisa de alguma ajuda?

**Comment by dansenpir** [comment]
@veronicasvalerio, precisamos fechar essa task até no máximo dia 18 desse mês.
Qual o status? Necessita de ajuda?

**Comment by dansenpir** [comment]
@veronicasvalerio, dei alguns toques lá na página da Wiki e acredito que com isso a gente consiga fechar a task até dia 25. Depois me retorne se precisa de ajuda, por favor.

**Comment by dansenpir** [comment]
Como estamos, @veronicasvalerio?

**Comment by veronicasvalerio** [comment]
@dansenpir finalizei no dia 24.08.
Você poderia verificar, por favor?
Perdão por não deixar registrado aqui.

**Comment by veronicasvalerio** [comment]
@dansenpir 
Você poderia validar por favor!
https://github.com/SouJunior-Labs/project-list/wiki/Draft.-Pap%C3%A9is-de-cada-%C3%A1rea-em-um-projeto-de-software

**Comment by djhonantanparreira** [comment]
Página da Wiki validada, portanto essa issue foi fechada.
