### ISSUE TITLE
Etapas de um projeto de software

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#126]
**Descrição**:
Necessário criar uma página na Wiki descrevendo as etapas presentes durante a elaboração de um produto sob a ótica de projeto de software, levando em consideração os cargos presentes no servidor SouJunior Lab.

**Motivação**:
Atualmente muitos evitam de criar projetos ou até criam, mas não tem muita noção das etapas que compõem a criação de um produto ou não entendem todo o fluxo de um projeto de software, então essa página visa sanar essa problemática.

**Link da página na Wiki**
https://github.com/SouJunior-Lab/project-list/wiki/%5BDraft%5D-Etapas-de-um-projeto-de-software

**O que deve ser feito nessa task:**
- [ ] Elaboração de uma página na Wiki com o compilado das informações presentes na task #124 ;
- [ ] Validação da página Wiki.

**Relação**
Essa tarefa está diretamente relacionada a #124

**Comment by AlecLimaDev** [comment]
@dansenpir 

Como descrito na minha task, quando tento criar na existente não vai.

Segue o link: https://github.com/SouJunior-Lab/project-list/wiki/Draft.-Etapas-de-um-projeto-de-Software

**Comment by dansenpir** [comment]
@AlecLimaDev, ficou bom.
Basta adicionar os menus de voltar para a página de projetos e de ir para a Home, nesse novo formato da Wiki.

**Comment by dansenpir** [comment]
@AlecLimaDev, adicionei o novo banner nessa página da Wiki, mas ficou faltando os menus de navegação.

**Comment by dansenpir** [comment]
Task finalizada.
