### ISSUE TITLE
Meme Battle

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#146]
**Descrição enviada pelo formulário de registro de projeto**:
""A ideia do projeto é um jogo de browser online em grupo.

A ideia do MVP é:

Cada grupo de jogador inicia um jogo com X rodadas.

1 Etapa da rodada:
o jogador da vez será responsável por criar uma frase que usaria em um meme.

2 Etapa:
cada jogador terá que escolher um meme (dentre algumas alternativas) que mais ficaria engraçado/mais combina com a frase.

3 Etapa:
iniciará uma votação anônima para cara combinação, e o mais bem votado pontua.

O jogo acaba quando um jogador atingir X pontos.

Existem algumas variações que podemos acrescentar como inverter a ordem, invés de criar uma frase para os outros jogadores escolherem um meme, escolher um meme para cada jogador criar uma frase.

Outra variação seria poder enviar o próprio meme invés de escolher um pré definido, entre outras.""

**Founder**:
Usuário Discord: lucasca#2104

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [x] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by dansenpir** [comment]
@veronicasvalerio, como está essa task? Precisa de ajuda?

**Comment by veronicasvalerio** [comment]
@dansenpir tenho conversado quase que diariamente com o Founder pedindo para ele finalizar as regras para podermos dar continuidade, da última vez (ontem) disse que ia pedir para alguém finalizar. Vou esperar mais 01 dia.

**Comment by dansenpir** [comment]
@veronicasvalerio, o Founder havia um post no fórum de recrutamento, porém a última interação dele foi há 10 dias.

Entendo que o projeto não é a prioridade dele no momento e o cargo que o permitia prosseguir com o recrutamento foi removido.

Por favor, comunique que entendemos as ações dele como desistência e que caso queira criar um novo projeto ou reiniciar este, que verifique se possui tempo hábil para dar prosseguimento.

Task encerrada.

**Comment by veronicasvalerio** [comment]
@dansenpir tinha criado o canal no Servidor da Sou Jr Labs, devo deletar?

**Comment by dansenpir** [comment]
@veronicasvalerio 

Os canais e cargo do projeto só devem ser criados após a aceitação do Pull Request.

Conversei com o Founder no domingo e alinhamos que ele poderia iniciar um novo recrutamento para preencher as vagas remanescentes, porém dando uma atenção ao post, respondendo todos os interessados.

Até o momento não foi iniciado um novo recrutamento, então seria bom conversar com o Founder, questionando se possui alguma dúvida e se precisa de ajuda.

**Comment by dansenpir** [comment]
@veronicasvalerio vou atribuir essa task a um Guardian.

**Comment by dansenpir** [comment]
@priscillatrevizan pretendo atribuir a algum Guardian novato, mas ainda não entraram na org, mesmo assim já te designei essa task, para que você possa acompanhar em conjunto, pois dúvidas certamente existirão.

**Comment by priscillatrevizan** [comment]
@dansenpir atualização: Avisei founder sobre criação do cargo Meme Battle, e ele foi orientado sobre forúm de weekly e chat. Expliquei sobre o envio semanal da weekly conforme wiki e pedi que na primeira weekly nos informe todas as pessoas já recrutadas para que possamos fornecer os cargos. Ele disse que provavelmente já consiga fazer o 1º envio essa semana.
Coloquei-me à disposição para dúvidas, e permaneço em acompanhamento.

**Comment by dansenpir** [comment]
Certo, @priscillatrevizan.
Cinco dias se passaram e não houve envio da Weekly.
Verifique depois com o Founder sobre isso.

Aliás, não esqueça de remover o cargo de Founder temporário e adicionar os "permanentes".

**Comment by priscillatrevizan** [comment]
@dansenpir weekly publicada e founder orientado! 🎉
