### ISSUE TITLE
[Sugestão] Time fixo SouJunior Labs

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#149]
![Image](https://github.com/SouJunior/soujunior-lab/assets/22007659/f644dc0d-c24d-432e-b70a-a50ee44b3054)

**A fazer**
- [x] Entender a sugestão junto ao autor (usuário Discord: _ralfizin_);
- [x] Analisar possibilidade de adoção da sugestão.

**Comment by salviotonon** [comment]
###  Sugestão levantada junto com o usuário Discord: ralfizin;

**A ideia proposta pelo membro Attila Abreu é formar um time fixo na Sou Junior que seja responsável por fornecer suporte técnico aos demais times**. Esse time seria composto por pessoas engajadas e com conhecimentos especializados nas áreas de Front-end, Back-end, UX, PM (Gerenciamento de Projetos) e Agilidade.

- A proposta funcionaria da seguinte maneira: quando um líder de projeto necessitar de suporte em uma área específica, ele faria uma solicitação ao **time de suporte da Sou Junior**. O time de suporte, por sua vez, marcaria uma call ou reunião para ajudar o time solicitante, compartilhando conhecimentos, oferecendo orientações e auxiliando na resolução de problemas técnicos ou desafios relacionados ao projeto.

### Análise da possibilidade de adoção da sugestão.

Para realizar essa ideia, eu imagino alguns pontos chaves:

1. Identificar os membros engajados e com conhecimentos especializados nas áreas de Front-end, Back-end, UX, PM e Agilidade. Essas pessoas seriam os integrantes do time de suporte.

2. Definir os critérios para solicitação de suporte, como por exemplo, o líder de projeto enviar uma solicitação formal especificando a área em que precisa de ajuda e as necessidades específicas.

3. Estabelecer um sistema de agendamento de calls ou reuniões entre o time de suporte e o time solicitante. Isso pode ser feito por meio de uma canal especifico no discord.

Durante a call ou reunião, os membros do time de suporte devem se disponibilizar para esclarecer dúvidas, compartilhar boas práticas, fornecer orientações e ajudar a encontrar soluções para os desafios apresentados.

**Comment by dansenpir** [comment]
ii e iii: Um fórum criado para isso e seu espaço de comentários creio que resolveria isso.

i. A questão seria como fazer isso. É difícil encontrar pessoas engajadas e com tempo de ajudar. Ralfizin propôs alguma solução para isso?

**Comment by salviotonon** [comment]
@dansenpir O usuário que levantou a ideia, começou a conversar sobre com o @cplxx, vi que no lugar desse time fixo, poderia ser um evento de tempos em tempos para auxílio dos projetos. Trocariamos esse "time fixo" por um evento com foco nas problemáticas levantadas pelos founder. Cada evento teria seu escopo baseado nas solicitações dos founder. Como esse evento seria muito trabalhoso de organizar, não vejo algo que seja possível de se realizar frequentemente, seria melhor com datas espaçadas. Mas em resumo seria uma junção de todos os membros dos projetos da souJunior labs em uma data específica, tratando de problemas mais corriqueiros levantados pelos founders.

Nessa nova abordagem teríamos os seguintes problemas

- quem vai organizar o evento?
- como saberíamos qual os problemas corriqueiros dos founder (um formulário? Sair perguntando no PV?)
- quem faria a frente na hora da reunião, precisaríamos de alguém para tocar a reunião
- existe a possibilidade de alocar todos os membros em uma call simultânea?

**Comment by dansenpir** [comment]
Estou resolvendo isso na task #151.
