### ISSUE TITLE
[Sugestão] Padronização de ideal de projetos

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#150]
![Image](https://github.com/SouJunior/soujunior-lab/assets/22007659/9662eb1c-72b3-4ec8-ab17-f0fcd051a071)

**A fazer**
- [x] Entender a sugestão junto ao autor (usuário Discord: _calmond_);
- [ ] Analisar possibilidade de adoção da sugestão.

**Comment by dansenpir** [comment]
@iltrd, essa task foi inicializada?

**Comment by iltrd** [comment]
@dansenpir Ainda não, essa semana focarei nela

**Comment by iltrd** [comment]
@dansenpir task iniciada hoje. Entrei em contato com o autor da sugestão e por enquanto estou aguardando respostas.

**Comment by iltrd** [comment]
Foi me passado a ideia de inserir a visão do produto baseado no Lean Inception. Sendo uma forma de fundamentar mais a ideia do projeto e ficar mais claro para quem possa ter interesse. 
Com isso, acho que podemos incluir as seguintes perguntas no formulário para entrar como projeto na soujunior labs. 

[Visão do produto](https://fga-eps-mds.github.io/2021.1-Cartografia-social-docs/lean/lean-inception.html#atividade-1-visao-do-produto)

![Image](https://github.com/SouJunior/soujunior-lab/assets/66341343/a774097e-a63a-48bb-8345-3b3aad4f0c32)

Fiz um rascunho de como pensei em agregar essa visão de produto junto do formulário. 
https://forms.gle/Ce6sP9F9yw3nXAqL6

O que você acha @dansenpir ?

**Comment by dansenpir** [comment]
> Foi me passado a ideia de inserir a visão do produto baseado no Lean Inception. Sendo uma forma de fundamentar mais a ideia do projeto e ficar mais claro para quem possa ter interesse. Com isso, acho que podemos incluir as seguintes perguntas no formulário para entrar como projeto na soujunior labs.
> 
> [Visão do produto](https://fga-eps-mds.github.io/2021.1-Cartografia-social-docs/lean/lean-inception.html#atividade-1-visao-do-produto)
> 
> ![Image](https://user-images.githubusercontent.com/66341343/256698121-a774097e-a63a-48bb-8345-3b3aad4f0c32.png)
> 
> Fiz um rascunho de como pensei em agregar essa visão de produto junto do formulário. https://forms.gle/Ce6sP9F9yw3nXAqL6
> 
> O que você acha @dansenpir ?

Eu entendo que a nível de registro de projetos essas informações não são tão relevantes, sendo o mais importante mesmo os contatos do Founder.

Enxergo isso mais para o momento de recrutamento ou algum momento próximo disso.

Também não consegui pensar uma forma automatizada de incluir isso no nosso fluxo.

Qual a visão do autor da sugestão sobre isso? Onde ele imagina que esse fluxo se encaixe?

**Comment by dansenpir** [comment]
@priscillatrevizan, consegue entrar em contato com o Calmond e checar como ele imagina isso fazendo parte do nosso fluxo?
Caso ele não tenha algo mapeado, apenas informe que não conseguimos encontrar uma forma de incluir isso ao nosso processo, mas que agradecemos a sugestão e pedimos desculpas pela demora no retorno.

**Comment by priscillatrevizan** [comment]
Atualização:
Conversei com o Calmond em 14/08 e inicialmente a idéia dele era mesmo a aplicação de um filtro no formulário de inscrição do projeto mesmo, como a Letícia relatou acima. Mas evolui com ele que os dados que recebemos nesse formulário são de uso somente para nosso controle, e não repassamos adiante, ou seja, não atenderia o requisito que ele pretende, que é uma correta divulgação do produto aos membros.
Sendo assim, ele sugeriu que para o nosso fluxo fosse adotado um padrão de post de recrutamento, e ele usou como exemplo o post do "diário das emoções" que possuía uma formatação confusa. Pedi a ele uma sugestão de modelo, segue o que ele passou:

O [nome do produto] é [um app? Um site?] que [explicação do produto] 

Recrutamos os papéis:

[Inserir papel] [inserir qnt de pessoas]

[Inserir papel] [inserir qnt de pessoas]

[Inserir papel] [inserir qnt de pessoas]

Segue também a justificativa dele para tal adoção (contextualizando): _"Esse fluxo se acertado o recrutamento deixaria de ser uma vitrine de ideias e passaria a ser uma vitrine de possíveis produtos
Muito mais fácil iniciar técnicas de Lean Inception, Design Thinking ou Design Sprint ( linha do Discovery)
Facilitaria a linha de recrutamento: Devs que sabem desenvolver aplicativos Android, por exemplo.
Então é um ponto de melhoria que faria com que o fluxo ficasse mais assertivo ao invés de subjetivo"_

De fato, já vi alguns posts de recrutamento confuso e confesso que enquanto moderadora já até pedi algumas correções. Acredito que esse fluxo pode ser algo facilmente adotado, colocando nas instruções do fórum e orientando os projetos com auxilio dos mods. O que acha @dansenpir ?

**Comment by dansenpir** [comment]
![Image](https://github.com/SouJunior/soujunior-labs/assets/22007659/85457ca4-c1ef-41a1-a108-46e78ccef71c)

Esse já é o modelo de publicação atual, não?

O que se espera é uma pressão maior dos Moderadores, é isso?

@priscillatrevizan

**Comment by priscillatrevizan** [comment]
@dansenpir  creio que ele queira que deixemos menos vago , ali diz "descrição do produto a ser desenvolvido" mas não define um modelo. Ele mencionou que precisa conter [nome do produto] é [um app? Um site?] que [explicação do produto].

E quanto a cobrança dos mods, confere.

**Comment by dansenpir** [comment]
Certo, @priscillatrevizan.
Vou transferir essa task para domínio dos moderadores.
Obrigado pela coleta de informações.

**Comment by dansenpir** [comment]
@veronicasvalerio @Gu-Parlandim @Soaressluiss 

Vou implementar isso nos próximos dias, quando me sobrar um tempo.
Peço que aproveitem o momento para sugerirem itens que sigam o mesmo roteiro e se inteirarem também desse fluxo, pois é algo que afeta bastante a forma como lidamos com recrutamento e precisarão estar cientes.
