### ISSUE TITLE
[Sugestão] Evento para troca de experiência das áreas

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#151]
![Image](https://github.com/SouJunior/soujunior-lab/assets/22007659/2f057c93-e32e-4754-b995-212ef84ba800)

**A fazer**
- [x] Entender a sugestão junto ao autor (usuário Discord: _ralfizin_);
- [x] Analisar possibilidade de adoção da sugestão.

**Comment by cplxx** [comment]
A ideia do Attila é basicamente uma network entre os projetos da souJunior ou seja um "evento" que reunisse os times, feito por nós com pautas para não ficar algo perdido. Como por exemplo falar e identificar problemas que travam os projetos e tentar solucionar com membros de outros times. 

Acho que é uma que pode ser pensada, pois é uma boa oportunidade dos times se conhecerem e criarem laços. Podemos falar com os founder de cada projetos e funcionar, pois creio que se não partir dos lideres, acho bem difícil de acontecer.

**Comment by dansenpir** [comment]
@cplxx, então seria um espécie de encontro dos projetos semanalmente com pautas? Attila chegou a dar exemplos de pautas?

**Comment by dansenpir** [comment]
Criado um canal no servidor e questionado aos Founders se é algo que desejam fazer acontecer, para identificação dos próximos passos.

**Comment by dansenpir** [comment]
Até o momento, 8 dos 21 projetos interagiram sobre a ideia, sendo a favor e propondo abordagens.
Estou analisando como implementar isso, ao passo que espero interação dos demais Founder e alavanco outros fluxos do servidor.
