### ISSUE TITLE
Ciclo

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#152]
**Descrição enviada pelo formulário de registro de projeto**:
""Um aplicativo com foco nos registros dos sintomas do ciclo menstrual das pessoas que menstruam, objetivando o acompanhamento da saúde íntima dela. Ao final de um certo período de dias, seria possível gerar um arquivo simples e de fácil entendimento (até mesmo um pdf compartilhável) tanto para a pessoa que menstrua quanto para o profissional da saúde sobre os dados colhidos durante o ciclo de modo que facilitem o serviço do ginecologista. O arquivo poderia conter informações sintetizadas tanto de 3 meses atrás, até 6 meses, por exemplo.

A ideia é se distanciar dos aplicativos com foco somente na pessoa que menstrua e previsão de menstruação, trazendo o profissional da saúde como alguém de interesse nas informações obtidas e como a pessoa capacitada para analisar os dados e realizar um real uso das informações obtidas.""

**Founder**:
Usuário Discord: annie.b

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [ ] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [ ] Criar o cargo do projeto;
- [ ] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [ ] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [ ] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [ ] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by priscillatrevizan** [comment]
Atualização: Aguardando founder, demora se deve pois ela está concluindo participação em um bootcamp. Pretende se focar no projeto a partir de agosto.

- Está a par do processo para iniciar já em recrutamento da equipe.
- 
Permaneço em acompanhamento.

**Comment by priscillatrevizan** [comment]
Fornecido cargo de founder e orientado sobre recrutamento: Relembrei importância de disponibilidade e conversamos sobre fórum busque-um-recruiter. Reforcei wiki (cargos necessários para validação do projeto)

Aguardando recrutamento para sequenciar.

**Comment by priscillatrevizan** [comment]
Atualização: Entrei em contato com founder em 09/08, relatou estar realizando recrutamento.

Entrei em contato hoje novamente, está sem luz na cidade e não pôde falar muito, mas relatou que o recrutamento está um pouco "empacado" e que acredita ser por conta dela. Estou no aguardo de mais informações.

**Comment by dansenpir** [comment]
@priscillatrevizan, a Founder desistiu do projeto?
Vi que o squad TechTalent cessou o recrutamento desse projeto.

Ou na realidade o time já está completo?

Tem 1 mês e meio que essa task foi criada, então o projeto já deveria estar em Stage 00.

O que acontece?

**Comment by priscillatrevizan** [comment]
Falei com ela essa semana @dansenpir , ela está com problemas pessoais. Segundo ela esta com a cachorrinha para morrer e é muito apegada, coisa que está afetando muito ela, e até para trabalhar está com dificuldade. Então ela preferiu esperar mais um pouco para reccrutar. Mas não quer desistir. Como fazemos nesse caso? fechamos a task e ela precisa refazer todo o processo quando quizer retomar? Pois não conseguiu me dar um prazo.
