### ISSUE TITLE
Sistema de Delivery

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#153]
**Descrição enviada pelo formulário de registro de projeto**:
"Um projeto que permite vendas de produtos online, para restaurantes, lanchonetes, com sistema de pagamento e entrega."

**Founder**:
Usuário Discord: IgorDeMoura

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [x] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by dansenpir** [comment]
@veronicasvalerio, verifiquei que os dois repositórios do projeto não possuem o tópico "soujunior-labs", favor solicitar ao Founder essa inclusão, pois é uma das regras de criação de projetos.

**Comment by veronicasvalerio** [comment]
@dansenpir entrei em contato com o Founder e fiz a solicitação.

**Comment by dansenpir** [comment]
@veronicasvalerio, esse card está em "To do". Está correto?

**Comment by dansenpir** [comment]
Task finalizada.
