### ISSUE TITLE
Diário das emoções

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#154]
**Descrição enviada pelo formulário de registro de projeto**:
"Aplicativo de registro de emoções e acompanhamento emocional."

**Founder**:
Usuário Discord:victor_yghor

**A fazer**

_Abordagem inicial_:
- [x] Verificar se o Founder já está em dois projetos, caso positivo informar que o limite são 2 projetos simultâneos, caso esteja em no máximo 1 projeto, continuar conforme abaixo;
- [x] Conceder os cargos "⚒┃Founder" e "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [ ] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [ ] Criar o cargo do projeto;
- [ ] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [ ] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [ ] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [ ] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação;
- [ ] Garantir que o Founder envie a primeira Weekly do projeto, solicitando a inclusão dos membros do projeto.

**Comment by priscillatrevizan** [comment]
Atualização: Founder banido do servidor por comportamento indevido.

PR fechado sem aceite.

@dansenpir essa task finaliza certo?

**Comment by dansenpir** [comment]
Isso, @priscillatrevizan.
