### ISSUE TITLE
MoradaApp

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#155]
**Descrição enviada pelo formulário de registro de projeto**:
"Desenvolver um sistema de gerenciamento online para o condomínio XYZ que facilite o agendamento do salão de festas, quadra de futebol, recebimento de sugestões e reclamações dos moradores, e melhore a comunicação interna."

**Founder**:
Usuário Discord: vrjack_

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Temporary Founder" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [x] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by dansenpir** [comment]
@LucasCarlos7, caso possua dúvidas, fale com a @priscillatrevizan.

**Comment by LucasCarlos7** [comment]
Okay 🤠

**Comment by dansenpir** [comment]
@LucasCarlos7, entrou em contato com o Founder?

**Comment by LucasCarlos7** [comment]
Já sim, aguardando retorno.

**Comment by LucasCarlos7** [comment]
Nessa abordagem, não é necessário o envio do formulário?

**Comment by priscillatrevizan** [comment]
@LucasCarlos7  o formulário de inscrição do projeto você diz?Se for, nesse caso aqui o envio já foi realizado e passou pelo Dan, ele transformou em task de acordo com as informações que vieram do founder pra vc dar prosseguimento.

**Comment by LucasCarlos7** [comment]
Ah sim, agora faz sentido para mim, obrigado 🙂

**Comment by LucasCarlos7** [comment]
@priscillatrevizan poderia por favor verificar se todas as etapas foram feitas corretamente?
Principalmente a criação do canal sobre as permissões, nao sei se tenho essa permissão para verifica isso ou talvez eu nn tenha achado mesmo.
