### ISSUE TITLE
TechRoom

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#156]
**Descrição enviada pelo formulário de registro de projeto**:
"O projeto TechRoom tem como objetivo criar uma rede social inovadora, inspirada no conceito do LinkedIn, mas com um foco distinto. A proposta é oferecer um ambiente digital no qual profissionais de diferentes áreas, como desenvolvimento, marketing, design, finanças, recursos humanos, investidores e muito mais, possam se conectar, expandir suas redes de contatos e, potencialmente, iniciar empreendimentos conjuntos."

**Founder**:
Usuário Discord: riccskn#8740

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Temporary Founder" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [ ] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by dansenpir** [comment]
@elda-paz, entrou em contato com o Founder?

**Comment by elda-paz** [comment]
sim, estou dando prosseguimento conforme o mesmo vai me passando os ajustes.
No momento ira começar o recrutamento.

**Comment by dansenpir** [comment]
Card movido para "In Progress".

**Comment by priscillatrevizan** [comment]
Estamos em processo de correção do repositório para público.
