### ISSUE TITLE
Trilha DesenvolveXP

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-labs#157]
**Descrição enviada pelo formulário de registro de projeto**:
""Criar um ambiente onde iniciantes na área de tecnologia possam ter seu primeiro contato com projetos reais, com times de desenvolvimento, recrutamento para esse time e que possam receber ajuda de mentores, também com a possibilidade de empresas utilizarem os projetos como cases para recrutamento.
Funcionalidades da Plataforma:
Oferecer projetos pré-definidos com níveis de dificuldade variados, ter tempo pré-estipulado para qualquer um dos projetos e após esse tempo passar não seja possível a análise do mesmo. Permitir que os usuários escolham trabalhar individualmente ou em equipe na resolução dos projetos.
Mentores:
Cargo de mentor é destinado para pessoas com XP na área de tecnologia e que queiram ajudar na plataforma. Eles serão responsáveis em introduzir novos projetos, em que será obrigatório ao receber o cargo adicionar 1 projeto em um determinado tempo. Exigir que os mentores avaliem projetos concluídos antes de adicionar novos projetos à plataforma e poder estar dentro de equipes, quantidade de projetos analisados também será pré-estabelecida. Permitir que mentores orientem iniciantes e também forneçam orientação para equipes.
Verificação de Projetos:
Garantir que todos os projetos sejam revisados e verificados antes de serem disponibilizados na plataforma. Utilizar critérios de qualidade para aprovação dos projetos. Também que não sou copias de projetos já existentes.
Transparência e Acesso ao Código:
Manter todos os projetos concluídos no perfil do usuário, permitindo que outros vejam e aprendam com o trabalho. Disponibilizar o código escrito nos projetos concluídos para fins educacionais e que também seja possível ver andamento de projetos.
Utilização de APIs e Verificação de Autoria:
Integrar a plataforma com APIs, como a GitHub, para verificar a autoria dos projetos. Evitar a submissão de projetos plagiados ou não autorais.
Destaque para Projetos Verificados:
Destacar os projetos que foram revisados e aprovados por mentores na plataforma.
Perfil e Selos de Mentor:
Atribuir um selo aos mentores para indicar sua experiência na plataforma. Mostrar informações sobre os projetos que os mentores analisaram e as equipes que eles compõem.
Gerenciamento de Times:
Permitir que os usuários criem equipes, gerenciem os membros e monitorem o progresso do projeto de cada membro.
Empresas e Recrutamento:
Oferecer às empresas a oportunidade de criar projetos públicos na plataforma para testes de recrutamento. E também criação de projetos privados para teste de codagem que ficaram disponíveis no perfil do participante. Fornece um ambiente onde as empresas possam avaliar as habilidades dos candidatos por meio da resolução de projetos.""

**Founder**:
Usuário Discord: amora_kawaii

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Temporary Founder" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o canal de Weekly do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos;
- [x] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by priscillatrevizan** [comment]
Atualização: Realizado call tira dúvidas hoje. Iniciará solicitação de recrutamento no fórum busque-recruiter nos próximos dias. Acompanhando.

**Comment by priscillatrevizan** [comment]
A founder estava sem computador por mais de uma semana, está em processo de realizar o PR entre ontem e hoje.
