### ISSUE TITLE
Padronização dos projetos

### ISSUE THREAD

**Issue by ralacerda** [SouJunior/soujunior-labs#99]
Olá,
Eu gostaria de tomar a iniciativa de ajudar na padronização dos projetos.

Iria facilitar quando os membros precisam criar novos projetos, fazer mudanças, etc.
Além disso, com regras claras a se seguir, menos chances de pedir modificações no PR, e as mudanças podem ser aceitas com mais velocidade.

Depois de fazer toda a padronização, podemos incluir um comentário em markdown com algumas informações, por exemplo, como fazer um link em markdown, como saber o slug do header para adicionar no index, e também incluir um "template" para um projeto.

Algumas diferenças entre projetos que eu percebi:

- Links
Existe uma mistura de `<a>` e `<a target="_blank">` em vez do formato natural do markdown `[Nome do link](link)`. 
Eu acho que o formato em markdown é mais fácil de escrever e ler, e `target="_blank"` não funciona no github.

 - Ordem e espaçamento
 Alguns projetos possuem o responsável dentro da equipe, outros possuem o responsável no topo, temos o link do repositório antes e outros depois da descrição. Também acho que um espaço entre os parágrafos pode deixar mais fácil de ler poderia ser padronizado.

- Tamanho da descrição
Alguns projetos se limitaram a uma descrição de somente um parágrafo, enquanto outros usam multiplos.

- Tipo de lista e separação
Somente alguns projetos possuem a formatação correta de lista do Markdown. A lista do Markdown além de adicionar os pontos em cada linha, também aumenta o espaçamento, o que facilita a leitura. Padronizando e criando um template, todos os projetos futuros conseguirão seguir o mesmo formato facilmente.
Grupos também separam de formas diferentes os membros da mesma equipe. Alguns optam por `|` outros separam usando `e`.

Estou me colocando a disposição para:
- Modificar todos os projetos para se adequar ao formato decidido.
- Criação de comentários em Markdown para auxiliar colaboradores
- Template para novos projetos
- Reviews de PR, indicando quais mudanças precisam ser feitas para se adequar ao formato determinado.

Acho que cada padronização pode ser uma PR diferente. Por exemplo, já posso mudar todos os links para o formato de Markdown enquanto a gente discute os outros pontos.

**Comment by dansenpir** [comment]
Saudações, @ralacerda!
Perdão pela demora no retorno, mas só tive tempo de te responder por agora.
Tenho o desejo de padronizar as coisas por aqui, porém nunca me sobrou tempo para isso, então te respondendo:

**Links:**
Realmente é uma melhor abordagem seguir o formato Markdown.

**Ordem e espaçamento:**
De fato.

**Tamanho da descrição:**
Acredito que três ou quatro linhas sejam mais do que o suficiente para a descrição dos projetos.

**Tipo de lista e separação**
Novamente, seria melhor o formato em Markdown mesmo.
Quanto a separação, considero o pipe uma alternativa melhor.

Por favor, sinta-se livre para enviar os PR's com as correções sugeridas e obrigado pela ajuda!
